### ISSUE TITLE
Plugin not working in Sketch 72 version 

### ISSUE THREAD

**Issue by roberthuston66** [rodi01/RenameIt#148]

**Comment by bomberstudios** [comment]
Just opened a pull request that fixes this issue

**Comment by rodi01** [comment]
Any chance someone can test this build?
https://www.dropbox.com/s/dl/sv8n0fpp6nfnesb/Rename-It-4.5.4.sketchplugin.zip

I no longer have the latest version of Sketch to test it.

**Comment by prvg** [comment]
Just tried it in Sketch 72.0 – doesn't work for me. Thanks for being on it! 
Found this, where they mentioned the usage of an unofficial class by some plug-ins. https://spectrum.chat/sketch/bug-reports/cant-find-variable-msapplicationmetadata~0b44ab46-59e5-4736-b10c-4ec6e083d949

**Comment by rodi01** [comment]
@prvg any chance you can post the console error?

**Comment by prvg** [comment]
`ReferenceError: Can't find variable: MSApplicationMetadata
    at . (/node_modules/sketch-module-google-analytics/index.js@/Users/philippreinhart-vangulpen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:1992:36)
    at __webpack_require__ (/Users/philippreinhart-vangulpen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:27:34)
    at . (/src/lib/TheUI.js@/Users/philippreinhart-vangulpen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:5215:107)
    at __webpack_require__ (/Users/philippreinhart-vangulpen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:27:34)
    at . (/src/commandFindReplace.js@/Users/philippreinhart-vangulpen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:4729:87)
    at __webpack_require__ (/Users/philippreinhart-vangulpen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:27:34)
    at /Users/philippreinhart-vangulpen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:91:37
    at __skpm_run (/Users/philippreinhart-vangulpen/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:92:12)
    at __skpm_run[native code] (/)`

**Comment by prvg** [comment]
```
ReferenceError: Can't find variable: MSApplicationMetadata
    at . (/node_modules/sketch-module-google-analytics/index.js@/Users/johndoe/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:1992:36)
    at __webpack_require__ (/Users/johndoe/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:27:34)
    at . (/src/lib/TheUI.js@/Users/johndoe/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:5215:107)
    at __webpack_require__ (/Users/johndoe/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:27:34)
    at . (/src/commandFindReplace.js@/Users/johndoe/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:4729:87)
    at __webpack_require__ (/Users/johndoe/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:27:34)
    at /Users/johndoe/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:91:37
    at __skpm_run (/Users/johndoe/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Rename-It-4.5.4.sketchplugin/Contents/Sketch/commandFindReplace.js:92:12)
    at __skpm_run[native code] (/)
```

**Comment by rodi01** [comment]
@prvg thanks! I will see if I can fix this.

**Comment by bomberstudios** [comment]
Again: this PR I opened yesterday fixes this issue https://github.com/rodi01/RenameIt/pull/149

**Comment by rodi01** [comment]
> Again: this PR I opened yesterday fixes this issue #149

I compiled from your PR and people are still having issues.

**Comment by bomberstudios** [comment]
Ah, sorry, I thought you had missed my comment 🙈

One thing you could try is make sure you clean your `node_modules` folder. I made some changes in package versions and that might explain the issues you're seeing.

Also: please email me at ale@sketch.com and I'll make sure you get a license for the current version (I can't imagine how frustrating it must be to work on this blindly 😬)

**Comment by rodi01** [comment]
@prvg Here is a new build: https://www.dropbox.com/s/sv8n0fpp6nfnesb/Rename-It-4.5.4.sketchplugin.zip?dl=1

@bomberstudios thanks for your help. I followed your instructions and recompiled the plugin. Hopefully, it works now. FYI, I sent you an email.

**Comment by Sketch-User** [comment]
@rodi01 it Works

**Comment by caliiope** [comment]
Oh my God it's working ! Thank you so much !! I thought I was going nuts !

**Comment by rodi01** [comment]
Awesome! I'll publish the update now.

**Comment by roberthuston66** [comment]
Awesome, thank you so much! 🎉
